/**
 * Official product URLs keyed by Brand.canonicalName (phase-6 P1 seed).
 * Variants that share a product site map to the same URL.
 */
const GROUPS: Record<string, readonly string[]> = {
  "https://1password.com": ["1Password"],
  "https://www.adp.com/what-we-offer/products/adp-workforce-now.aspx": ["ADP Workforce Now"],
  "https://abnormalsecurity.com": ["Abnormal Security"],
  "https://www.accuranker.com": ["AccuRanker"],
  "https://www.activecampaign.com": ["ActiveCampaign"],
  "https://business.adobe.com/products/analytics/adobe-analytics.html": ["Adobe Analytics"],
  "https://business.adobe.com/products/campaign/adobe-campaign.html": ["Adobe Campaign"],
  "https://business.adobe.com/products/magento/magento-commerce.html": [
    "Adobe Commerce",
    "Adobe Commerce (Magento)",
    "Magento",
    "Magento (Adobe Commerce)",
  ],
  "https://www.adobe.com/products/firefly.html": ["Adobe Firefly"],
  "https://www.adobe.com/products/illustrator.html": ["Adobe Illustrator"],
  "https://www.adobe.com/products/photoshop.html": ["Adobe Photoshop"],
  "https://www.adobe.com/products/xd.html": ["Adobe XD"],
  "https://affinity.serif.com/en-us/designer/": ["Affinity Designer"],
  "https://www.aha.io": ["Aha!"],
  "https://ahrefs.com": ["Ahrefs"],
  "https://www.airtable.com": ["Airtable Automations"],
  "https://www.amazon.com/b?node=15547130011": ["Amazon Drive"],
  "https://sell.amazon.com": ["Amazon Seller Central"],
  "https://apps.ankiweb.net": ["Anki"],
  "https://answerthepublic.com": ["AnswerThePublic"],
  "https://www.icloud.com/notes": ["Apple Notes"],
  "https://www.icloud.com": [
    "Apple iCloud",
    "Apple iCloud Drive",
    "iCloud",
    "iCloud Drive",
    "iCloud+",
  ],
  "https://support.apple.com/en-us/109016": ["Apple iCloud Keychain", "iCloud Keychain"],
  "https://asana.com": ["Asana"],
  "https://www.ashbyhq.com": ["Ashby"],
  "https://www.atlassian.com": ["Atlassian"],
  "https://www.automate.com": ["Automate"],
  "https://www.automationanywhere.com": ["Automation Anywhere"],
  "https://www.avoma.com": ["Avoma"],
  "https://www.axure.com": ["Axure RP"],
  "https://azure.microsoft.com/en-us/products/devops": ["Azure DevOps", "Azure Repos"],
  "https://www.babbel.com": ["Babbel"],
  "https://www.backblaze.com": ["Backblaze"],
  "https://balsamiq.com": ["Balsamiq"],
  "https://www.bamboohr.com": ["BambooHR"],
  "https://basecamp.com": ["Basecamp"],
  "https://bear.app": ["Bear"],
  "https://www.bigcommerce.com": ["BigCommerce", "BigCommerce Enterprise"],
  "https://bitbucket.org": ["Bitbucket"],
  "https://bitwarden.com": ["Bitwarden"],
  "https://boomi.com": ["Boomi"],
  "https://www.box.com": ["Box"],
  "https://www.braze.com": ["Braze"],
  "https://breezy.hr": ["Breezy HR"],
  "https://www.brevo.com": ["Brevo", "SendinBlue"],
  "https://buffer.com": ["Buffer"],
  "https://www.busuu.com": ["Busuu"],
  "https://buzzsumo.com": ["BuzzSumo"],
  "https://www.canva.com": ["Canva"],
  "https://capacities.io": ["Capacities"],
  "https://www.careerbuilder.com": ["CareerBuilder"],
  "https://chatgpt.com": ["ChatGPT"],
  "https://www.chorus.ai": ["Chorus"],
  "https://circleci.com": ["CircleCI"],
  "https://claude.ai": ["Claude"],
  "https://www.clearscope.io": ["Clearscope"],
  "https://clickup.com": ["ClickUp"],
  "https://clipdrop.co": ["Clipdrop"],
  "https://www.close.com": ["Close"],
  "https://www.clozemaster.com": ["Clozemaster"],
  "https://coda.io": ["Coda"],
  "https://cofense.com": ["Cofense"],
  "https://www.atlassian.com/software/confluence": ["Confluence"],
  "https://www.constantcontact.com": ["Constant Contact"],
  "https://www.contentful.com": ["Contentful"],
  "https://convertkit.com": ["ConvertKit"],
  "https://copilot.microsoft.com": ["Copilot", "Microsoft Copilot"],
  "https://www.copper.com": ["Copper"],
  "https://www.copy.ai": ["Copy.ai"],
  "https://www.coursera.org": ["Coursera", "Coursera for Business"],
  "https://www.craft.do": ["Craft"],
  "https://www.crowdstrike.com": ["CrowdStrike Falcon"],
  "https://github.com/cleverhans-lab/cleverhans": ["CleverHans"],
  "https://customer.io": ["Customer"],
  "https://www.cyberghostvpn.com": ["CyberGhost"],
  "https://www.d-id.com": ["D-ID"],
  "https://openai.com/dall-e-3": ["DALL·E"],
  "https://www.darktrace.com": ["Darktrace", "Darktrace/Email"],
  "https://www.dashlane.com": ["Dashlane"],
  "https://www.datacamp.com": ["DataCamp"],
  "https://www.deel.com": ["Deel"],
  "https://www.descript.com": ["Descript"],
  "https://www.docker.com": ["Docker"],
  "https://stability.ai": ["DreamStudio", "Stable Diffusion"],
  "https://www.drift.com": ["Drift"],
  "https://www.drip.com": ["Drip"],
  "https://www.dropbox.com": ["Dropbox", "Dropbox Business"],
  "https://languagedrops.com": ["Drops"],
  "https://www.duolingo.com": ["Duolingo", "Duolingo Max"],
  "https://www.ecwid.com": ["Ecwid"],
  "https://elicit.com": ["Elicit"],
  "https://www.enpass.io": ["Enpass"],
  "https://www.etsy.com": ["Etsy"],
  "https://evernote.com": ["Evernote"],
  "https://www.expensify.com": ["Expensify"],
  "https://expressjs.com": ["Express.js"],
  "https://www.expressvpn.com": ["ExpressVPN"],
  "https://blackforestlabs.ai": ["FLUX"],
  "https://fathom.video": ["Fathom"],
  "https://fellow.app": ["Fellow"],
  "https://www.figma.com": ["Figma"],
  "https://fireflies.ai": ["Fireflies"],
  "https://www.framer.com": ["Framer"],
  "https://www.frase.io": ["Frase"],
  "https://www.freshbooks.com": ["FreshBooks"],
  "https://www.freshworks.com/freshdesk": ["Freshdesk"],
  "https://www.freshworks.com/crm": [
    "Freshsales",
    "Freshsales (Freshworks CRM)",
    "Freshworks",
  ],
  "https://front.com": ["Front"],
  "https://www.futurelearn.com": ["FutureLearn"],
  "https://gemini.google.com": ["Gemini"],
  "https://www.getresponse.com": ["GetResponse"],
  "https://git-scm.com": ["Git"],
  "https://github.com/features/actions": ["GitHub Actions"],
  "https://github.com/features/copilot": ["GitHub Copilot"],
  "https://github.com/features/issues": ["GitHub Projects"],
  "https://about.gitlab.com": ["GitLab", "GitLab CI/CD"],
  "https://www.glassdoor.com": ["Glassdoor"],
  "https://www.gong.io": ["Gong"],
  "https://marketingplatform.google.com/about/analytics/": ["Google Analytics 4"],
  "https://assistant.google.com": ["Google Assistant"],
  "https://chat.google.com": ["Google Chat"],
  "https://www.google.com/drive": ["Google Drive"],
  "https://keep.google.com": ["Google Keep"],
  "https://ads.google.com/home/lib_zulu/keyword-planner/": ["Google Keyword Planner"],
  "https://passwords.google.com": ["Google Password Manager"],
  "https://search.google.com/search-console": ["Google Search Console"],
  "https://www.gorgias.com": ["Gorgias"],
  "https://grain.com": ["Grain"],
  "https://www.grammarly.com": ["Grammarly"],
  "https://www.greenhouse.com": ["Greenhouse"],
  "https://grok.x.ai": ["Grok"],
  "https://www.getguru.com": ["Guru"],
  "https://gusto.com": ["Gusto"],
  "https://www.getharvest.com": ["Harvest"],
  "https://www.heap.io": ["Heap"],
  "https://www.hellotalk.com": ["HelloTalk"],
  "https://www.helpscout.com": ["Help Scout"],
  "https://www.heygen.com": ["HeyGen"],
  "https://www.hibob.com": ["Hibob"],
  "https://www.hirevue.com": ["HireVue"],
  "https://hiverhq.com": ["Hiver"],
  "https://www.honeybook.com": ["HoneyBook"],
  "https://hootsuite.com": ["Hootsuite"],
  "https://www.hubspot.com": [
    "HubSpot",
    "HubSpot CMS",
    "HubSpot Email Marketing",
    "HubSpot Marketing Hub",
    "HubSpot Sales Hub",
    "HubSpot Service Hub",
    "HubSpot Workflows",
  ],
  "https://www.ibm.com/qradar": ["IBM QRadar"],
  "https://www.idrive.com": ["IDrive"],
  "https://ifttt.com": ["IFTTT"],
  "https://www.ipvanish.com": ["IPVanish"],
  "https://www.ivpn.net": ["IVPN"],
  "https://ideogram.ai": ["Ideogram"],
  "https://www.invisionapp.com": ["InVision"],
  "https://www.indeed.com": ["Indeed", "Indeed Hiring Platform"],
  "https://www.insightly.com": ["Insightly"],
  "https://www.make.com": ["Integromat", "Make"],
  "https://www.jetbrains.com/idea/": ["IntelliJ IDEA", "JetBrains IntelliJ IDEA"],
  "https://www.jetbrains.com": ["JetBrains IDEs"],
  "https://www.intercom.com": ["Intercom"],
  "https://invoiceninja.com": ["Invoice Ninja"],
  "https://iterable.com": ["Iterable"],
  "https://www.jasper.ai": ["Jasper"],
  "https://www.jazzhr.com": ["JazzHR"],
  "https://www.jenkins.io": ["Jenkins"],
  "https://www.atlassian.com/software/jira": ["Jira", "Jira Software"],
  "https://www.atlassian.com/software/jira/service-management": ["Jira Service Management"],
  "https://joplinapp.org": ["Joplin"],
  "https://www.kashoo.com": ["Kashoo"],
  "https://www.kayako.com": ["Kayako"],
  "https://keepass.info": ["KeePass"],
  "https://keepassxc.org": ["KeePassXC"],
  "https://www.keepersecurity.com": ["Keeper"],
  "https://www.khanacademy.org": ["Khan Academy"],
  "https://kissflow.com": ["Kissflow"],
  "https://www.klaviyo.com": ["Klaviyo"],
  "https://klingai.com": ["Kling AI"],
  "https://kubernetes.io": ["Kubernetes"],
  "https://www.kustomer.com": ["Kustomer"],
  "https://www.lastpass.com": ["LastPass"],
  "https://later.com": ["Later"],
  "https://lattice.com": ["Lattice"],
  "https://leonardo.ai": ["Leonardo.ai"],
  "https://www.lever.co": ["Lever"],
  "https://linear.app": ["Linear"],
  "https://www.lingq.com": ["LingQ"],
  "https://www.lingodeer.com": ["LingoDeer"],
  "https://www.linkedin.com": ["LinkedIn"],
  "https://www.linkedin.com/jobs": ["LinkedIn Jobs"],
  "https://www.linkedin.com/learning": ["LinkedIn Learning"],
  "https://www.linkedin.com/talent": ["LinkedIn Recruiter", "LinkedIn Talent Solutions"],
  "https://www.livechat.com": ["Livechat"],
  "https://logseq.com": ["Logseq"],
  "https://loops.so": ["Loops"],
  "https://lumalabs.ai/dream-machine": ["Luma Dream Machine"],
  "https://mega.io": ["MEGA"],
  "https://mailchimp.com": ["Mailchimp"],
  "https://www.mailerlite.com": ["MailerLite"],
  "https://www.marketmuse.com": ["MarketMuse"],
  "https://business.adobe.com/products/marketo/adobe-marketo.html": ["Marketo (Adobe)"],
  "https://marvelapp.com": ["Marvel"],
  "https://www.masterclass.com": ["MasterClass"],
  "https://maven.com": ["Maven"],
  "https://meetgeek.ai": ["MeetGeek"],
  "https://www.memrise.com": ["Memrise"],
  "https://www.microsoft.com/microsoft-365": ["Microsoft 365"],
  "https://www.microsoft.com/security/business/microsoft-defender": [
    "Microsoft Defender",
    "Microsoft Defender for Office 365",
  ],
  "https://www.microsoft.com/en-us/dynamics-365": [
    "Microsoft Dynamics 365",
    "Microsoft Dynamics 365 Sales",
  ],
  "https://www.microsoft.com/edge": ["Microsoft Edge"],
  "https://www.microsoft.com/microsoft-365/onedrive/online-cloud-storage": [
    "Microsoft OneDrive",
    "OneDrive",
  ],
  "https://www.microsoft.com/microsoft-365/onenote/digital-note-taking-app": [
    "Microsoft OneNote",
    "OneNote",
  ],
  "https://www.microsoft.com/microsoft-365/planner": ["Microsoft Planner"],
  "https://www.microsoft.com/en-us/power-platform/products/power-automate": [
    "Microsoft Power Automate",
  ],
  "https://www.microsoft.com/en-us/microsoft-365/project/project-management-software": [
    "Microsoft Project",
  ],
  "https://www.microsoft.com/en-us/security/business/siem-and-xdr/microsoft-sentinel": [
    "Microsoft Sentinel",
  ],
  "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software": ["Microsoft Teams"],
  "https://www.midjourney.com": ["Midjourney"],
  "https://www.mimecast.com": ["Mimecast Email Security"],
  "https://miro.com": ["Miro", "Miro AI"],
  "https://mixpanel.com": ["Mixpanel"],
  "https://monday.com": ["Monday", "Monday Sales CRM", "Monday.com Sales CRM"],
  "https://www.mondly.com": ["Mondly"],
  "https://www.monster.com": ["Monster"],
  "https://moz.com": ["Moz Pro"],
  "https://www.mulesoft.com": ["MuleSoft"],
  "https://mullvad.net": ["Mullvad VPN"],
  "https://www.namely.com": ["Namely"],
  "https://nextcloud.com": ["Nextcloud"],
  "https://nordpass.com": ["NordPass"],
  "https://nordvpn.com": ["NordVPN"],
  "https://www.notion.com": ["Notion"],
  "https://www.notta.ai": ["Notta"],
  "https://obsidian.md": ["Obsidian"],
  "https://www.omnisend.com": ["Omnisend"],
  "https://www.beondeck.com": ["On Deck"],
  "https://www.opencart.com": ["OpenCart"],
  "https://www.oracle.com/human-capital-management/": ["Oracle Cloud HCM", "Oracle HCM Cloud"],
  "https://otter.ai": ["Otter"],
  "https://www.outreach.io": ["Outreach"],
  "https://www.pabbly.com/connect/": ["Pabbly Connect"],
  "https://www.paloaltonetworks.com/cortex": [
    "Palo Alto Networks Cortex XDR",
    "Palo Alto Networks Cortex XSIAM",
  ],
  "https://parabola.io": ["Parabola"],
  "https://www.paypal.com": ["PayPal", "PayPal Invoicing"],
  "https://www.paychex.com": ["Paychex Flex"],
  "https://www.paycom.com": ["Paycom"],
  "https://www.paycor.com": ["Paycor"],
  "https://www.paylocity.com": ["Paylocity"],
  "https://penpot.app": ["Penpot"],
  "https://www.perplexity.ai": ["Perplexity"],
  "https://www.personio.com": ["Personio"],
  "https://pictory.ai": ["Pictory"],
  "https://pika.art": ["Pika Labs"],
  "https://www.pimsleur.com": ["Pimsleur"],
  "https://pipedream.com": ["Pipedream"],
  "https://www.pipedrive.com": ["Pipedrive"],
  "https://www.pluralsight.com": ["Pluralsight"],
  "https://www.podia.com": ["Podia"],
  "https://preply.com": ["Preply"],
  "https://www.privateinternetaccess.com": ["Private Internet Access"],
  "https://www.productboard.com": ["Productboard"],
  "https://www.proofpoint.com": ["Proofpoint", "Proofpoint Email Protection"],
  "https://www.protopie.io": ["ProtoPie"],
  "https://proton.me/drive": ["Proton Drive"],
  "https://proton.me/pass": ["Proton Pass"],
  "https://protonvpn.com": ["Proton VPN"],
  "https://www.purevpn.com": ["PureVPN"],
  "https://www.jetbrains.com/pycharm/": ["PyCharm"],
  "https://quickbooks.intuit.com": [
    "QuickBooks Desktop",
    "QuickBooks Online",
    "QuickBooks Self-Employed",
  ],
  "https://quizlet.com": ["Quizlet"],
  "https://recurly.com": ["Recurly"],
  "https://www.read.ai": ["Read"],
  "https://www.relay.app": ["Relay"],
  "https://www.rev.com": ["Rev"],
  "https://www.rippling.com": ["Rippling"],
  "https://roamresearch.com": ["Roam Research"],
  "https://www.roboform.com": ["RoboForm"],
  "https://www.rosettastone.com": ["Rosetta Stone"],
  "https://runwayml.com": ["Runway"],
  "https://www.sap.com/products/hcm.html": ["SAP SuccessFactors", "SAP SuccessFactors Recruiting"],
  "https://seranking.com": ["SE Ranking"],
  "https://www.sage.com": ["Sage Business Cloud Accounting"],
  "https://www.salesforce.com": [
    "Salesforce",
    "Salesforce Commerce Cloud",
    "Salesforce Essentials",
    "Salesforce Marketing Cloud",
    "Salesforce Sales Cloud",
    "Salesforce Service Cloud",
  ],
  "https://www.scholarcy.com": ["Scholarcy"],
  "https://scite.ai": ["Scite"],
  "https://www.screamingfrog.co.uk/seo-spider/": ["Screaming Frog", "Screaming Frog SEO Spider"],
  "https://www.sembly.ai": ["Sembly", "Sembly AI"],
  "https://www.semrush.com": ["Semrush", "Semrush Site Audit"],
  "https://www.sentinelone.com": ["SentinelOne", "SentinelOne Singularity"],
  "https://www.servicenow.com": ["ServiceNow"],
  "https://www.shopify.com": ["Shopify"],
  "https://shortcut.com": ["Shortcut"],
  "https://sitebulb.com": ["Sitebulb"],
  "https://www.sketch.com": ["Sketch"],
  "https://www.skillshare.com": ["Skillshare"],
  "https://slab.com": ["Slab"],
  "https://slack.com": ["Slack"],
  "https://slite.com": ["Slite"],
  "https://www.smartrecruiters.com": ["SmartRecruiters"],
  "https://www.smartsheet.com": ["Smartsheet"],
  "https://openai.com/sora": ["Sora"],
  "https://www.speak.com": ["Speak"],
  "https://speechling.com": ["Speechling"],
  "https://www.splunk.com": ["Splunk Enterprise Security"],
  "https://sproutsocial.com": ["Sprout Social"],
  "https://www.spyfu.com": ["SpyFu"],
  "https://squareup.com": ["Square", "Square Invoices", "Square Online"],
  "https://www.squarespace.com": ["Squarespace Commerce"],
  "https://online.stanford.edu": ["Stanford"],
  "https://www.storybook.js.org": ["Storybook"],
  "https://stripe.com": ["Stripe", "Stripe Billing", "Stripe Invoicing"],
  "https://sublime.security": ["Sublime Security"],
  "https://www.sugarcrm.com": ["SugarCRM"],
  "https://surferseo.com": ["Surfer SEO", "SurferSEO"],
  "https://surfshark.com": ["Surfshark"],
  "https://www.sync.com": ["Sync"],
  "https://www.synthesia.io": ["Synthesia"],
  "https://www.tabnine.com": ["Tabnine"],
  "https://tactiq.io": ["Tactiq"],
  "https://tana.inc": ["Tana"],
  "https://www.tandem.net": ["Tandem"],
  "https://teachable.com": ["Teachable"],
  "https://www.teamwork.com": ["Teamwork"],
  "https://www.thinkific.com": ["Thinkific"],
  "https://www.tidio.com": ["Tidio"],
  "https://todoist.com": ["Todoist"],
  "https://tray.ai": ["Tray"],
  "https://trello.com": ["Trello"],
  "https://tresorit.com": ["Tresorit"],
  "https://www.tunnelbear.com": ["TunnelBear"],
  "https://www.ukg.com": ["UKG Pro"],
  "https://www.uxpin.com": ["UXPin"],
  "https://neilpatel.com/ubersuggest/": ["Ubersuggest"],
  "https://www.udacity.com": ["Udacity"],
  "https://www.udemy.com": ["Udemy"],
  "https://www.uipath.com": ["UiPath"],
  "https://uizard.io": ["Uizard"],
  "https://code.visualstudio.com": ["VS Code", "Visual Studio Code"],
  "https://www.vectra.ai": ["Vectra AI"],
  "https://www.vyprvpn.com": ["VyprVPN"],
  "https://www.waveapps.com": ["Wave", "Wave Accounting"],
  "https://webflow.com": ["Webflow"],
  "https://windscribe.com": ["Windscribe"],
  "https://www.wireguard.com": ["WireGuard"],
  "https://www.wix.com": ["Wix eCommerce"],
  "https://woocommerce.com": ["WooCommerce"],
  "https://wordpress.org": ["WordPress"],
  "https://www.workable.com": ["Workable"],
  "https://www.workato.com": ["Workato"],
  "https://www.workday.com": ["Workday", "Workday HCM", "Workday Recruiting"],
  "https://www.wrike.com": ["Wrike"],
  "https://www.xero.com": ["Xero"],
  "https://www.yale.edu": ["Yale"],
  "https://zapier.com": ["Zapier"],
  "https://www.zendesk.com": ["Zendesk", "Zendesk Suite", "Zendesk Support"],
  "https://www.zenefits.com": ["Zenefits"],
  "https://zeplin.io": ["Zeplin"],
  "https://www.ziprecruiter.com": ["ZipRecruiter"],
  "https://www.zoho.com/books/": ["Zoho Books"],
  "https://www.zoho.com/crm/": ["Zoho CRM"],
  "https://www.zoho.com/desk/": ["Zoho Desk"],
  "https://www.zoho.com/invoice/": ["Zoho Invoice"],
  "https://zoom.us": ["Zoom"],
  "https://www.zuora.com": ["Zuora"],
  "https://www.ebay.com": ["eBay"],
  "https://www.edx.org": ["edX"],
  "https://www.italki.com": ["italki"],
  "https://n8n.io": ["n8n"],
  "https://www.pcloud.com": ["pCloud"],
  "https://tldv.io": ["tl;dv"],
};

function flatten(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [url, names] of Object.entries(GROUPS)) {
    for (const name of names) out[name] = url;
  }
  return out;
}

export const BRAND_WEBSITES = flatten();
