import { normalizeBrandKey } from "@/lib/brand-keys";
const RAW_PREFERRED: Record<string, string> = {
  // Google / Gemini
  "google bard": "Gemini",
  "google gemini": "Gemini",
  "google bard/gemini": "Gemini",
  "google bard / gemini": "Gemini",
  bard: "Gemini",
  "google gemini / imagen": "Gemini",
  imagen: "Gemini",
  veo: "Gemini",
  "google workspace ai": "Google Workspace",

  // OpenAI / ChatGPT product variants.
  // Keep the company name "OpenAI" separate for entity/visibility analysis.
  "openai's gpt": "ChatGPT",
  "openai's gpt-3": "ChatGPT",
  "openai's gpt-4": "ChatGPT",
  "openai's chatgpt": "ChatGPT",
  "openai chatgpt": "ChatGPT",
  "evolved chatgpt": "ChatGPT",
  "gpt-4": "ChatGPT",
  "gpt 4": "ChatGPT",
  "gpt-4o": "ChatGPT",
  "gpt-5": "ChatGPT",
  "chat gpt": "ChatGPT",
  "chatgpt advanced data analysis": "ChatGPT",

  // Anthropic / Claude product variants.
  // Keep the company name "Anthropic" separate.
  "claude ai": "Claude",
  "claude 3": "Claude",
  "anthropic's claude": "Claude",

  // Microsoft Copilot (no bare "copilot")
  "microsoft copilot": "Microsoft Copilot",
  "microsoft 365 copilot": "Microsoft Copilot",
  "microsoft bing chat": "Microsoft Copilot",

  // Products
  "jasper ai": "Jasper",
  "notion ai": "Notion",
  "github copilot": "GitHub Copilot",
  "copy ai": "Copy.ai",
  "copy.ai": "Copy.ai",
  copy: "Copy.ai",
  "microsoft visual studio": "Visual Studio",
  "swagger/openapi tools": "Swagger",
  alexa: "Amazon Alexa",
  "midjourney ai": "Midjourney",
  "mid journey": "Midjourney",
  "bing image creator": "Microsoft Designer",
  "gmail smart compose": "Gmail Smart Compose",
  "enhanced asana": "Asana",
  teams: "Microsoft Teams",
  azure: "Microsoft Azure",
  "hubspot crm": "HubSpot",
  "perplexity ai": "Perplexity",
  "einstein ai": "Salesforce",

  // VPN product aliases
  protonvpn: "Proton VPN",
  "proton vpn (free tier)": "Proton VPN",
  mullvad: "Mullvad VPN",
  pia: "Private Internet Access",
  "pia (private internet access)": "Private Internet Access",
  "private internet access (pia)": "Private Internet Access",
  "surfshark vpn": "Surfshark",
  "surfshark (business plan)": "Surfshark",

  // Password manager SKUs → product
  "1password teams": "1Password",
  "1password business": "1Password",
  "1password business/teams": "1Password",
  "1password for teams": "1Password",
  "1password for teams/business": "1Password",
  "lastpass business": "LastPass",
  "lastpass teams": "LastPass",
  "bitwarden teams/enterprise": "Bitwarden",
  "bitwarden teams / enterprise": "Bitwarden",
  "keeper security": "Keeper",
  "keeper business": "Keeper",
  "keeper business/enterprise": "Keeper",
  "keeper business / enterprise": "Keeper",
  "keeper for business": "Keeper",
  "keeper for teams": "Keeper",
  "keeper security business/enterprise": "Keeper",
  "keeper security enterprise": "Keeper",
  "dashlane for business": "Dashlane",
  "dashlane business": "Dashlane",
  "bitwarden enterprise": "Bitwarden",
  "nordpass teams": "NordPass",
  "proton pass for business": "Proton Pass",
  "apple icloud keychain/passwords": "Apple iCloud Keychain",
  "apple passwords": "Apple iCloud Keychain",
  "apple keychain": "Apple iCloud Keychain",
  "keepass/keepassxc": "KeePassXC",

  // AI Image / Video
  "stability ai's stable diffusion": "Stable Diffusion",
  "adobe's firefly": "Adobe Firefly",
  "runwayml's gen-2": "Runway",
  "runway gen-2": "Runway",
  "runway gen-3": "Runway",
  "runway gen-3 alpha": "Runway",
  "runway gen3": "Runway",
  "runway gen-2/gen-3": "Runway",
  "runway gen-2 / gen-3": "Runway",
  runwayml: "Runway",
  // preprocessBrand strips ".ai", so Leonardo.ai and Leonardo share key "leonardo".
  // In ranking data this almost always means the image product, not SAP Leonardo.
  leonardo: "Leonardo.ai",
  "leonardo ai": "Leonardo.ai",
  "leonardo.ai": "Leonardo.ai",
  ideogram: "Ideogram",
  "ideogram.ai": "Ideogram",
  "sora by openai": "Sora",
  "openai sora": "Sora",
  sora: "Sora",
  "midjourney v5": "Midjourney",
  "midjourney v6": "Midjourney",
  "midjourney v7": "Midjourney",
  // OpenAI image line — keep separate from ChatGPT chat product.
  "dall-e mini": "Craiyon",
  "openai dall·e": "DALL·E",
  "openai dall-e": "DALL·E",
  "openai's dall-e": "DALL·E",
  "openai's dall·e": "DALL·E",
  "dall-e 2": "DALL·E",
  "dall-e 3": "DALL·E",
  "dall·e 2": "DALL·E",
  "dall·e 3": "DALL·E",
  "dall-e": "DALL·E",
  "dall e": "DALL·E",
  "chatgpt / gpt image": "DALL·E",
  "chatgpt / gpt image 2": "DALL·E",
  "chatgpt / gpt-4o or gpt image": "DALL·E",
  "gpt image": "DALL·E",
  "gpt image 2": "DALL·E",
  "synthesys ai studio": "Synthesys",
  // Community nickname for Gemini image generation.
  "nano banana": "Gemini",
  "nano banana 2": "Gemini",
  "stable diffusion xl": "Stable Diffusion",
  "stable diffusion 3": "Stable Diffusion",
  "stable diffusion 3/xl": "Stable Diffusion",
  "sdxl": "Stable Diffusion",
  "canva ai": "Canva",
  "canva's magic studio": "Canva",

  // --- P6 SKU / slash-compound merges (cross-category) ---
  "otter.ai pro max": "Otter",
  "otter pro max": "Otter",
  "fireflies.ai 3.0": "Fireflies",
  "fireflies 3.0": "Fireflies",
  "notion ai meetings": "Notion",
  "microsoft copilot for meetings": "Microsoft Copilot",
  "shopify/shopify plus": "Shopify",
  "shopify / shopify plus": "Shopify",
  "shopify v2": "Shopify",
  "shopify plus": "Shopify",
  "crowdstrike falcon / charlotte ai": "CrowdStrike Falcon",
  "crowdstrike falcon/charlotte ai": "CrowdStrike Falcon",
  "crowdstrike charlotte ai / falcon next-gen siem": "CrowdStrike Falcon",
  "crowdstrike falcon insight xdr": "CrowdStrike Falcon",
  "falcon platform": "CrowdStrike Falcon",
  "microsoft defender for endpoint/xdr": "Microsoft Defender",
  "microsoft defender for endpoint": "Microsoft Defender",
  "palo alto cortex xsiam / cortex agentix": "Cortex XSIAM",
  "cortex xsiam / cortex agentix": "Cortex XSIAM",
  "fin ai 3.0": "Fin",
  "freshdesk/freshservice": "Freshdesk",
  "freshdesk / freshservice": "Freshdesk",
  "hubspot crm (sales hub)": "HubSpot",
  "sales hub": "HubSpot",
  "einstein forecasting": "Salesforce",
  "einstein gpt": "Salesforce",
  "salesforce starter suite": "Salesforce",
  "microsoft dynamics 365 customer engagement": "Microsoft Dynamics 365",
  "adobe xd / creative cloud suite": "Adobe XD",
  "adobe creative cloud": "Adobe Creative Cloud",
  "git/github": "GitHub",
  "git / github": "GitHub",
  "microsoft project / project for the web": "Microsoft Project",
  "microsoft project / planner": "Microsoft Project",
  "microsoft 365 / office 365": "Microsoft 365",
  "oracle taleo / oracle recruiting cloud": "Oracle Taleo",
  "sage 50cloud / sage 50": "Sage 50cloud",
  "runway ml": "Runway",
};

export const PREFERRED_CANONICAL: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_PREFERRED).map(([k, v]) => [normalizeBrandKey(k), v])
);

export function preferredCanonicalName(name: string): string {
  return PREFERRED_CANONICAL[normalizeBrandKey(name)] ?? name;
}

export { normalizeBrandKey } from "@/lib/brand-keys";
