export const HOME_METHODOLOGY_SECTIONS = [
  {
    title: "What GEO Radar Measures",
    paragraphs: [
      "GEO Radar measures AI visibility: how often products and brands appear in recommendations generated by ChatGPT, Gemini, and Grok. Traditional search asks whether a brand ranks on a results page; AI search asks which products make the shortlist, where they appear, and how consistently they are recommended.",
      "The result is a weekly signal for teams working on AI visibility and Generative Engine Optimization (GEO). Rankings indicate presence in the recommendation layer, not universal product quality.",
    ],
  },
  {
    title: "Prompt and Engine Coverage",
    paragraphs: [
      "Each category uses a fixed set of realistic discovery prompts covering comparison, use case, role, workflow, and common constraints. The same prompts run every week, reducing the chance that ranking changes are caused only by wording.",
      "The collection covers ChatGPT, Gemini, and Grok. A product may be highly visible in one assistant and absent in another, so the overall board and engine views together show both market presence and model-specific gaps.",
    ],
  },
  {
    title: "Scoring Signals",
    paragraphs: [
      "The score combines appearance rate, average position, and model coverage. This rewards products that appear consistently, appear near the top of shortlists, and are visible across more than one AI engine.",
      "Mentions are normalized to canonical product records so aliases do not split a score. Ambiguous or new mentions can receive human review before they affect a published ranking.",
    ],
  },
  {
    title: "Weekly Publishing and Interpretation",
    paragraphs: [
      "Each category publishes a weekly Top 20 board with overall and engine-specific views. Week-over-week movement shows whether a brand is gaining, losing, or newly entering AI search rankings.",
      "Use the leaderboard as a visibility benchmark and trend signal. A rising score may reflect stronger positioning, documentation, public discussion, or model behavior; it is not a universal quality score for every buyer or use case.",
    ],
  },
];

export const CATEGORY_INTROS: Record<
  string,
  {
    title: string;
    lead: string;
    paragraphs: string[];
    highlights: string[];
  }
> = {
  "ai-tools": {
    title: "The AI tools shortlist this week",
    lead:
      "When people ask ChatGPT, Gemini, or Grok which AI tool to use, these are the products that make the cut.",
    paragraphs: [
      "We run the same discovery prompts every week — assistants, copilots, research, writing, automation — then rank who gets mentioned most, how high they appear, and whether they show up across engines. Use this board to see who AI is pushing into the consideration set right now.",
    ],
    highlights: [
      "Top 20 by AI recommendation presence",
      "Overall + ChatGPT / Gemini / Grok tabs",
      "Week-over-week movers included",
    ],
  },
  "saas-software": {
    title: "The SaaS shortlist AI is giving buyers",
    lead:
      "Buyers ask AI for CRMs, project tools, and ops software. This board shows which products land in those answers.",
    paragraphs: [
      "Every Monday we score SaaS products on how often they appear in AI recommendations, how high they rank in the shortlist, and how many engines mention them. Watch who enters, who rises, and who drops out of AI’s default suggestions.",
    ],
    highlights: [
      "Business software recommendation visibility",
      "Buyer-style prompts, same set each week",
      "Competitive movement you can track Monday to Monday",
    ],
  },
  "ai-image-video-tools": {
    title: "Which creative AI tools made the cut",
    lead:
      "Image and video tools rise and fall fast. This ranking shows who AI is recommending for generative media right now.",
    paragraphs: [
      "We ask ChatGPT, Gemini, and Grok the same creative discovery prompts each week — image gen, video, design, social assets — and publish who shows up. If a tool isn’t on this board, it’s harder for AI-led creators to discover it.",
    ],
    highlights: [
      "Image, video, and creative tooling visibility",
      "Fast-moving category, weekly refresh",
      "Cross-engine coverage in one view",
    ],
  },
  "developer-tools": {
    title: "What AI tells developers to use",
    lead:
      "Developers ask AI which IDE, database, or infra tool to pick. Here’s who ends up on that shortlist.",
    paragraphs: [
      "GEO Radar tracks coding, infrastructure, data, testing, and observability products across ChatGPT, Gemini, and Grok. The Top 20 reflects who AI repeatedly names — not who has the most stars on GitHub.",
    ],
    highlights: [
      "Dev tools AI actually names in answers",
      "Overall board plus per-engine views",
      "Useful for DevRel and competitive GEO",
    ],
  },
  "marketing-tools": {
    title: "The marketing stack AI recommends",
    lead:
      "Marketers ask AI for SEO, email, analytics, and growth tools. This board shows which platforms get named.",
    paragraphs: [
      "Same prompts every week across three engines. Scores reward products that appear often, near the top, and across more than one assistant — so you can see who owns the AI recommendation narrative in marketing software.",
    ],
    highlights: [
      "SEO, content, email, analytics, growth software",
      "Weekly Top 20 with engine breakdowns",
      "A direct signal for GEO and product marketing",
    ],
  },
};
