import { formatEngineList } from "@/lib/constants";

const ENGINE_COPY = formatEngineList();

export const HOME_METHODOLOGY_SECTIONS = [
  {
    title: "What GEO Radar Measures",
    paragraphs: [
      "GEO Radar measures AI visibility: how often products and brands appear in recommendations generated by leading AI engines. Traditional search asks whether a brand ranks on a results page; AI search asks which products make the shortlist, where they appear, and how consistently they are recommended.",
      "The result is a weekly signal for teams working on AI visibility and Generative Engine Optimization (GEO). Rankings indicate presence in the recommendation layer, not universal product quality.",
    ],
  },
  {
    title: "Prompt and Engine Coverage",
    paragraphs: [
      "Each category uses a fixed set of realistic discovery prompts covering comparison, use case, role, workflow, and common constraints. The same prompts run every week, reducing the chance that ranking changes are caused only by wording.",
      `The collection covers ${ENGINE_COPY}. A product may be highly visible in one assistant and absent in another, so the overall board and engine views together show both market presence and model-specific gaps.`,
    ],
  },
  {
    title: "Scoring Signals",
    paragraphs: [
      "The score combines appearance rate, average position, and model coverage. This rewards products that appear consistently, appear near the top of shortlists, and are visible across more than one AI engine.",
      "Mentions are normalized to canonical product records so aliases do not split a score. Ambiguous or new mentions can receive human review before they affect a published ranking.",
    ],
  },
  {
    title: "Weekly Publishing and Interpretation",
    paragraphs: [
      "Each category publishes a weekly Top 20 board with overall and engine-specific views. Week-over-week movement shows whether a brand is gaining, losing, or newly entering AI search rankings.",
      "Use the leaderboard as a visibility benchmark and trend signal. A rising score may reflect stronger positioning, documentation, public discussion, or model behavior; it is not a universal quality score for every buyer or use case.",
    ],
  },
];

export const CATEGORY_INTROS: Record<
  string,
  {
    title: string;
    lead: string;
    paragraphs: string[];
    highlights: string[];
  }
> = {
  "ai-tools": {
    title: "The AI tools shortlist this week",
    lead:
      "See which assistants and copilots land in AI’s consideration set — so you spend less time on blind evals.",
    paragraphs: [
      "Picking assistants and copilots is expensive when every trial burns time and workflow changes. Check who AI defaults to this week before you decide what to test — and watch which competitors are moving in or out of the shortlist, instead of choosing on gut feel.",
    ],
    highlights: [
      "Top 20 by AI recommendation presence",
      "Overall + per-engine tabs",
      "Week-over-week movers included",
    ],
  },
  "saas-software": {
    title: "The SaaS shortlist AI is giving buyers",
    lead:
      "When buyers ask AI for CRMs, project tools, and ops software, this board shows who shows up in those answers.",
    paragraphs: [
      "CRM, project, and ops tools lock in process and switching costs once a team commits. See who AI puts in buyer answers this week before you shortlist demos — and track which competitors are rising or dropping out of those defaults.",
    ],
    highlights: [
      "Business software recommendation visibility",
      "Buyer-style prompts, same set each week",
      "Competitive movement you can track Monday to Monday",
    ],
  },
  "ai-image-video-tools": {
    title: "Which creative AI tools made the cut",
    lead:
      "See which image and video tools AI is naming for generative media right now.",
    paragraphs: [
      "For content and campaigns, swapping image or video tools can slow the whole pipeline. See who AI is pushing this week before you decide what to trial — and watch which competitors are moving on the shortlist, instead of picking on gut feel.",
    ],
    highlights: [
      "Image, video, and creative tooling visibility",
      "Fast-moving category, weekly refresh",
      "Cross-engine coverage in one view",
    ],
  },
  "developer-tools": {
    title: "What AI tells developers to use",
    lead:
      "When developers ask AI which IDE, database, or infra tool to pick, here’s who ends up on that shortlist.",
    paragraphs: [
      "IDE, database, and infra choices stick — a bad pick costs migration time later. See who AI names for engineers this week before you invest in evals — and track which competitors stay on (or fall off) that shortlist.",
    ],
    highlights: [
      "Dev tools AI actually names in answers",
      "Overall board plus per-engine views",
      "Useful for DevRel and competitive GEO",
    ],
  },
  "marketing-tools": {
    title: "The marketing stack AI recommends",
    lead:
      "When marketers ask AI for SEO, email, analytics, and growth tools, this board shows which platforms get named.",
    paragraphs: [
      "SEO, email, and analytics tools shape the whole growth loop; swapping mid-quarter is costly. See who AI recommends this week before you trial vendors — and watch which competitors are gaining or losing the recommendation slot.",
    ],
    highlights: [
      "SEO, content, email, analytics, growth software",
      "Weekly Top 20 with engine breakdowns",
      "A direct signal for GEO and product marketing",
    ],
  },
};
