import { normalizeBrandKey } from "@/lib/brand-keys";
import { toBrandSlug } from "@/lib/brand-slug";

/**
 * Curated P0-A preview data. The Company column always uses the recognizable
 * operator name, even when it is close to the product name.
 *
 * This file is staged locally for review; database relations are populated only
 * after the mapping has been approved.
 */
const RAW_PARENT_COMPANIES: Record<string, string> = {
  "dall-e": "OpenAI",
  "dall e": "OpenAI",
  "dall·e": "OpenAI",
  "stable diffusion": "Stability AI",
  "flux.1": "Black Forest Labs",
  "sap leonardo": "SAP",
  photoshop: "Adobe",
  ray2: "Luma AI",
  "deepai text to image api": "DeepAI",
  midjourney: "Midjourney",
  runway: "Runway",
  canva: "Canva",
  "canva magic write": "Canva",
  "canva's magic resize": "Canva",
  ideogram: "Ideogram",
  "pika labs": "Pika",
  synthesia: "Synthesia",
  lumen5: "Lumen5",
  pictory: "Pictory",
  visme: "Visme",
  heygen: "HeyGen",
  artbreeder: "Artbreeder",

  perplexity: "Perplexity AI",
  jasper: "Jasper AI",
  copy: "Copy.ai",
  grammarly: "Grammarly",
  "amazon alexa": "Amazon",
  tensorflow: "Google",
  siri: "Apple",
  "ibm watson": "IBM",
  "semantic scholar": "Allen Institute for AI",
  "amazon web services (aws) ai": "Amazon",
  "google ai": "Google",
  "slack ai": "Salesforce",
  "github copilot": "GitHub",

  bitbucket: "Atlassian",
  podman: "Red Hat",
  "postman cli": "Postman",
  "microsoft visual studio": "Microsoft",
  swagger: "SmartBear",
  "swagger/openapi tools": "SmartBear",
  "github codespaces": "GitHub",
  webstorm: "JetBrains",

  mailchimp: "Intuit",
  "google analytics 360": "Google",
  "hootsuite amplify": "Hootsuite",
  "marketo engage": "Adobe",
  "salesforce marketing cloud (pardot)": "Salesforce",

  slack: "Salesforce",
  trello: "Atlassian",
  "microsoft teams": "Microsoft",
  monday: "monday.com",
  "jira software": "Atlassian",
  quickbooks: "Intuit",
  "zoho crm": "Zoho",
  "sap crm/c4hana": "SAP",
  notion: "Notion Labs",
  // Commercial products with the same public-facing product/company name
  // are kept as owner data, but the table hides the duplicate label.
  docker: "Docker",
  circleci: "CircleCI",
  tabnine: "Tabnine",
  vercel: "Vercel",
  hubspot: "HubSpot",
  activecampaign: "ActiveCampaign",
  ahrefs: "Ahrefs",
  semrush: "Semrush",
  buffer: "Buffer",
  "sprout social": "Sprout Social",
  anyword: "Anyword",
  late: "Late",
  "constant contact": "Constant Contact",
  asana: "Asana",
  chargebee: "Chargebee",
  clickup: "ClickUp",
  zuora: "Zuora",
  outreach: "Outreach",
  freshbooks: "FreshBooks",
  discord: "Discord",
  recurly: "Recurly",

  duolingo: "Duolingo",
  "duolingo max": "Duolingo",
  "super duolingo": "Duolingo",
  babbel: "Babbel",
  "babbel live": "Babbel",
  "babbel live 3.0": "Babbel",
  "babbel live+": "Babbel",
  busuu: "Busuu",
  memrise: "Memrise",
  "memrise 4.0": "Memrise",
  pimsleur: "Simon & Schuster",
  "rosetta stone": "IXL Learning",
  hellotalk: "HelloTalk",
  tandem: "Tandem",
  lingodeer: "LingoDeer",
  lingq: "LingQ",
  italki: "italki",
  drops: "Kahoot",
  mondly: "Pearson",
  clozemaster: "Clozemaster",
  anki: "Anki",
  ankidroid: "Anki",
  ankimobile: "Anki",
  preply: "Preply",
  brainscape: "Brainscape",
  fluentu: "FluentU",
  "fluentu 2.0": "FluentU",
  speechling: "Speechling",
  talkpal: "Talkpal",
  speak: "Speak",
  immerse: "Immerse",

  // VPN — product ≠ operator
  nordvpn: "Nord Security",
  nordlayer: "Nord Security",
  surfshark: "Nord Security",
  expressvpn: "Kape Technologies",
  cyberghost: "Kape Technologies",
  "private internet access": "Kape Technologies",
  "proton vpn": "Proton",
  "mozilla vpn": "Mozilla",
  "perimeter 81": "Check Point",
  "cloudflare warp": "Cloudflare",
  "norton vpn": "Gen Digital",
  "hotspot shield": "Aura",
  ipvanish: "Ziff Davis",

  // Password managers
  nordpass: "Nord Security",
  "proton pass": "Proton",
  "apple icloud keychain": "Apple",
  "google password manager": "Google",
  "zoho vault": "Zoho",
  yubikey: "Yubico",
  "norton password manager": "Gen Digital",
  "azure ad": "Microsoft",
  chrome: "Google",
  keeper: "Keeper Security",

  // Ecommerce
  woocommerce: "Automattic",
  "salesforce commerce cloud": "Salesforce",
  "adobe commerce": "Adobe",
  "adobe commerce (magento)": "Adobe",
  "magento (adobe commerce)": "Adobe",
  "wix ecommerce": "Wix",
  square: "Block",
  "squarespace commerce": "Squarespace",
  "shopify/shopify plus": "Shopify",
  "shopify plus": "Shopify",
  "shopify v2": "Shopify",
  "shopify payments": "Shopify",
  "shopify magic": "Shopify",
  "shopify magic ai": "Shopify",
  "shopify b2b": "Shopify",

  // Online courses
  edx: "2U",
  linkedin: "Microsoft",
  udacity: "Accenture",
  "canvas lms": "Instructure",
  "blackboard learn ultra": "Anthology",
  codecademy: "Skillsoft",
  futurelearn: "SEEK",

  // Recruiting
  indeed: "Recruit Holdings",
  glassdoor: "Recruit Holdings",
  "linkedin jobs": "Microsoft",
  "workday recruiting": "Workday",
  "sap successfactors recruiting": "SAP",
  "oracle taleo / oracle recruiting cloud": "Oracle",

  // AI cybersecurity
  "crowdstrike falcon": "CrowdStrike",
  "crowdstrike falcon insight xdr": "CrowdStrike",
  "crowdstrike falcon / charlotte ai": "CrowdStrike",
  "falcon platform": "CrowdStrike",
  "crowdstrike charlotte ai / falcon next-gen siem": "CrowdStrike",
  "microsoft security": "Microsoft",
  "microsoft defender xdr": "Microsoft",
  "microsoft sentinel": "Microsoft",
  "microsoft defender for endpoint/xdr": "Microsoft",
  "palo alto cortex xsiam / cortex agentix": "Palo Alto Networks",
  "palo alto networks cortex xdr": "Palo Alto Networks",
  "proofpoint essentials": "Proofpoint",
  "proofpoint tap": "Proofpoint",
  "sentinelone singularity xdr": "SentinelOne",
  "torq ai soc platform": "Torq",

  // AI image / video SKUs
  "midjourney v6": "Midjourney",
  "chatgpt / gpt image 2": "OpenAI",
  "chatgpt / gpt image": "OpenAI",
  "chatgpt / gpt-4o or gpt image": "OpenAI",
  "runway gen-3 alpha": "Runway",
  luma: "Luma AI",

  // Meeting assistants
  otter: "Otter.ai",
  "otter.ai pro max": "Otter.ai",
  fireflies: "Fireflies.ai",
  "fireflies.ai 3.0": "Fireflies.ai",
  "notion ai meetings": "Notion Labs",
  "microsoft office": "Microsoft",
  "microsoft copilot for meetings": "Microsoft",

  // AI tools
  "google ai studio": "Google",
  "hugging face transformers": "Hugging Face",
  "apple intelligence pro": "Apple",
  "google workspace gemini": "Google",
  "miro ai": "Miro",
  "dall-e mini": "Craiyon",
  dialogflow: "Google",

  // Developer tools
  cursor: "Anysphere",
  openapi: "SmartBear",
  "swagger (openapi)": "SmartBear",
  "vs code": "Microsoft",
  soapui: "SmartBear",
  "github copilot workspace": "GitHub",
  "git/github": "GitHub",

  // SaaS SKUs
  "sales hub": "HubSpot",
  "service hub": "HubSpot",
  "stripe billing": "Stripe",
  "oracle netsuite": "Oracle",
  "sage intacct": "Sage",
  "microsoft 365 / office 365": "Microsoft",
  dynamics: "Microsoft",

  // Same public product / company name (P0-A still shows Company column)
  shopify: "Shopify",
  bigcommerce: "BigCommerce",
  etsy: "Etsy",
  prestashop: "PrestaShop",
  commercetools: "commercetools",
  "1password": "1Password",
  bitwarden: "Bitwarden",
  dashlane: "Dashlane",
  lastpass: "LastPass",
  roboform: "RoboForm",
  keepass: "KeePass",
  keepassxc: "KeePassXC",
  enpass: "Enpass",
  okta: "Okta",
  psono: "Psono",
  "mullvad vpn": "Mullvad",
  ivpn: "IVPN",
  windscribe: "Windscribe",
  "hide.me": "Hide.me",
  twingate: "Twingate",
  vyprvpn: "Golden Frog",
  tailscale: "Tailscale",
  coursera: "Coursera",
  udemy: "Udemy",
  skillshare: "Skillshare",
  pluralsight: "Pluralsight",
  maven: "Maven",
  teachable: "Teachable",
  masterclass: "MasterClass",
  thinkific: "Thinkific",
  datacamp: "DataCamp",
  "khan academy": "Khan Academy",
  kajabi: "Kajabi",
  "circle.so": "Circle",
  greenhouse: "Employ",
  lever: "Employ",
  ziprecruiter: "ZipRecruiter",
  smartrecruiters: "SmartRecruiters",
  workable: "Workable",
  ashby: "Ashby",
  icims: "iCIMS",
  jazzhr: "JazzHR",
  "breezy hr": "Breezy HR",
  "paradox (olivia)": "Paradox",
  seekout: "SeekOut",
  gem: "Gem",
  darktrace: "Darktrace",
  "vectra ai": "Vectra",
  fathom: "Fathom",
  grain: "Grain",
  avoma: "Avoma",
  "sembly ai": "Sembly",
  "tl;dv": "tl;dv",
  rev: "Rev",
  gong: "Gong",
  tactiq: "Tactiq",
  salesforce: "Salesforce",
  klaviyo: "Klaviyo",
  mailerlite: "MailerLite",
  contentstudio: "ContentStudio",
  amplitude: "Amplitude",
  productboard: "Productboard",
  "aha!": "Aha!",
  zotero: "Corporation for Digital Scholarship",
  jenkins: "Jenkins",
  "kubernetes (k8s)": "CNCF",
  helm: "CNCF",
  "synthesys ai studio": "Synthesys",
  "ticnote cloud": "TicNote",
  "cognitomeet": "CognitoMeet",
  "daily.dev recruiter": "daily.dev",

  // —— Phase 5 categories (company column overlay) ——
  // Project Management
  smartsheet: "Smartsheet",
  linear: "Linear",
  wrike: "Wrike",
  "monday work management": "monday.com",
  "monday.com ai work os": "monday.com",
  basecamp: "Basecamp",
  teamwork: "Teamwork",
  shortcut: "Shortcut",
  "jira work management": "Atlassian",
  "jira software (atlassian)": "Atlassian",
  "atlassian jira": "Atlassian",
  "jira cloud premium": "Atlassian",
  "microsoft project / project for the web": "Microsoft",
  "microsoft project / planner": "Microsoft",
  "microsoft project for the web": "Microsoft",
  "microsoft project/copilot": "Microsoft",
  "microsoft 365 project": "Microsoft",
  "microsoft teams + planner": "Microsoft",
  planner: "Microsoft",
  "clickup ai": "ClickUp",
  "asana intelligence": "Asana",
  "github projects": "GitHub",
  "oracle primavera": "Oracle",

  // CRM
  freshsales: "Freshworks",
  "freshsales (freshworks crm)": "Freshworks",
  "microsoft dynamics 365 sales": "Microsoft",
  "microsoft dynamics 365 crm": "Microsoft",
  "microsoft dynamics 365 customer engagement": "Microsoft",
  "microsoft dynamics 365 sales + copilot": "Microsoft",
  "salesforce sales cloud / einstein": "Salesforce",
  "salesforce starter suite": "Salesforce",
  "salesforce crm": "Salesforce",
  "salesforce sales/agentforce sales": "Salesforce",
  "einstein forecasting": "Salesforce",
  "sap sales cloud": "SAP",
  "sap c/4c": "SAP",
  "sap c/4hana": "SAP",
  "sap customer experience": "SAP",
  "sap customer experience (cx) suite": "SAP",
  "hubspot free/starter": "HubSpot",
  "hubspot starter": "HubSpot",
  "hubspot crm (sales hub)": "HubSpot",
  "hubspot crm (sales hub enterprise)": "HubSpot",
  "hubspot crm + sales hub": "HubSpot",
  "hubspot crm suite": "HubSpot",
  "hubspot sales hub / crm": "HubSpot",
  "hubspot sales hub / smart crm": "HubSpot",
  "hubspot smart crm / hubspot crm": "HubSpot",
  copper: "Copper",
  attio: "Attio",
  close: "Close",
  insightly: "Insightly",
  nethunt: "NetHunt",
  "zoho crm plus": "Zoho",
  "zoho crm (sales edition)": "Zoho",
  "zoho one": "Zoho",
  "oracle crm cloud": "Oracle",
  "pardot (by salesforce)": "Salesforce",
  clari: "Clari",
  pipedrive: "Pipedrive",

  // Customer Support / Helpdesk
  zendesk: "Zendesk",
  "zendesk suite": "Zendesk",
  "zendesk support": "Zendesk",
  "zendesk support suite": "Zendesk",
  "zendesk ai": "Zendesk",
  "zendesk ai suite": "Zendesk",
  "zendesk chat": "Zendesk",
  "zendesk guide": "Zendesk",
  freshdesk: "Freshworks",
  "freshdesk (freshworks)": "Freshworks",
  "freshdesk by freshworks": "Freshworks",
  "freshdesk/freshservice": "Freshworks",
  "freshdesk/freshworks": "Freshworks",
  "freshdesk/freshworks customer service": "Freshworks",
  "freshdesk neo": "Freshworks",
  freshworks: "Freshworks",
  intercom: "Intercom",
  "intercom + fin": "Intercom",
  "intercom infinity": "Intercom",
  "help scout": "Help Scout",
  gorgias: "Gorgias",
  "zoho desk": "Zoho",
  front: "Front",
  "jira service management": "Atlassian",
  kustomer: "Kustomer",
  liveagent: "LiveAgent",
  "servicenow customer service management": "ServiceNow",
  "servicenow customer service management (csm)": "ServiceNow",
  servicenow: "ServiceNow",

  // Accounting & Invoicing
  wave: "Wave",
  "wave financial": "Wave",
  "zoho books": "Zoho",
  "zoho invoice": "Zoho",
  holded: "Holded",
  intuit: "Intuit",
  "square invoices": "Block",
  "sage business cloud accounting": "Sage",
  "sage accounting": "Sage",
  "sage 50cloud": "Sage",
  "sage 50cloud / sage 50": "Sage",
  "teamsystem quipu": "TeamSystem",
  quipu: "TeamSystem",
  xero: "Xero",
  anfix: "Anfix",
  "stripe invoicing": "Stripe",
  "stripe billing + invoicing": "Stripe",
  "paypal invoicing": "PayPal",
  "quickbooks desktop": "Intuit",
  "quickbooks self-employed": "Intuit",
  "quickbooks solopreneur / quickbooks online": "Intuit",
  "quicken business & personal": "Intuit",
  freeagent: "FreeAgent",
  "invoice ninja": "Invoice Ninja",
  kashoo: "Kashoo",
  billage: "Billage",
  contasimple: "Contasimple",
  contasol: "Contasol",
  "a3innuva contabilidad": "A3innuva",
  odoo: "Odoo",

  // SEO / Content
  moz: "Moz",
  surferseo: "Surfer",
  "surfer ai": "Surfer",
  "surfer ai seo suite": "Surfer",
  "surferseo ai pro": "Surfer",
  "se ranking": "SE Ranking",
  clearscope: "Clearscope",
  frase: "Frase",
  "screaming frog": "Screaming Frog",
  "screaming frog seo spider": "Screaming Frog",
  marketmuse: "MarketMuse",
  sitebulb: "Sitebulb",
  spyfu: "SpyFu",
  mangools: "Mangools",
  ubersuggest: "Ubersuggest",
  "answer the public": "AnswerThePublic",
  answerthepublic: "AnswerThePublic",
  accuranker: "AccuRanker",
  serpstat: "SERPstat",
  sistrix: "Sistrix",
  deepcrawl: "Lumar",
  rankability: "Rankability",
  "ahrefs site audit": "Ahrefs",
  "ahrefs 3.0": "Ahrefs",
  "ahrefs core": "Ahrefs",
  "ahrefs keywords explorer": "Ahrefs",
  "semrush site audit": "Semrush",
  "semrush ai suite": "Semrush",
  "semrush keyword magic tool": "Semrush",
  "semrush nextgen": "Semrush",
  "google search console + lighthouse": "Google",
  keywordtool: "Keyword Tool",

  // Cloud Storage
  sync: "Sync.com",
  pcloud: "pCloud",
  "pcloud crypto": "pCloud",
  "apple icloud drive": "Apple",
  "apple icloud": "Apple",
  icloud: "Apple",
  "icloud drive": "Apple",
  "icloud+": "Apple",
  "icloud+ (apple)": "Apple",
  "icloud (apple)": "Apple",
  mega: "MEGA",
  "proton drive": "Proton",
  tresorit: "Tresorit",
  "google drive/workspace": "Google",
  "google drive (google workspace)": "Google",
  "google one": "Google",
  "amazon drive": "Amazon",
  "amazon photos": "Amazon",
  nextcloud: "Nextcloud",
  "microsoft onedrive": "Microsoft",
  "microsoft onedrive + sharepoint": "Microsoft",
  "microsoft onedrive/365": "Microsoft",
  "microsoft onedrive/microsoft 365": "Microsoft",
  "microsoft sharepoint/onedrive for business": "Microsoft",
  "onedrive/microsoft 365": "Microsoft",
  "onedrive/sharepoint": "Microsoft",
  sharepoint: "Microsoft",
  dropbox: "Dropbox",
  "dropbox paper": "Dropbox",
  box: "Box",
  "citrix sharefile": "Cloud Software Group",
  backblaze: "Backblaze",
  egnyte: "Egnyte",
  idrive: "IDrive",
  filen: "Filen",
  "aws s3": "Amazon",
  "spideroak one backup": "SpiderOak",
  cryptomator: "Cryptomator",

  // Design & Prototyping
  figma: "Figma",
  "figma dev mode": "Figma",
  "figma + dev mode": "Figma",
  framer: "Framer",
  sketch: "Sketch",
  penpot: "Penpot",
  protopie: "ProtoPie",
  webflow: "Webflow",
  "axure rp": "Axure",
  axure: "Axure",
  uxpin: "UXPin",
  "uxpin merge": "UXPin",
  "adobe xd / creative cloud suite": "Adobe",
  "creative cloud suite": "Adobe",
  "adobe illustrator": "Adobe",
  "adobe firefly": "Adobe",
  "affinity designer": "Canva",
  spline: "Spline",
  balsamiq: "Balsamiq",
  invision: "InVision",
  zeplin: "Zeplin",
  storybook: "Storybook",
  "autodesk fusion 360": "Autodesk",
  solidworks: "Dassault Systèmes",
  "stratasys j8 series": "Stratasys",
  "formlabs form 4/5/6": "Formlabs",
  keyshot: "Luxion",
  "uizard/banani": "Uizard",
  "magic patterns": "Magic Patterns",
  abstract: "Abstract",
  xometry: "Xometry",
  shapeways: "Shapeways",
  "hp jet fusion 5200/6400": "HP",

  // Note-taking & Knowledge Base
  obsidian: "Obsidian",
  "obsidian ai": "Obsidian",
  "atlassian confluence": "Atlassian",
  atlassian: "Atlassian",
  logseq: "Logseq",
  "microsoft onenote": "Microsoft",
  onenote: "Microsoft",
  "apple notes": "Apple",
  coda: "Coda",
  "roam research": "Roam Research",
  evernote: "Bending Spoons",
  capacities: "Capacities",
  craft: "Craft Docs",
  guru: "Guru",
  slite: "Slite",
  slab: "Slab",
  tana: "Tana",
  anytype: "Anytype",
  "google keep": "Google",
  "notion / notion ai": "Notion Labs",
  "notion ai+": "Notion Labs",
  "notion crm": "Notion Labs",
  memberful: "Memberful",

  // Email Marketing
  iterable: "Iterable",
  braze: "Braze",
  brevo: "Brevo",
  sendinblue: "Brevo",
  convertkit: "Kit",
  getresponse: "GetResponse",
  omnisend: "Omnisend",
  drip: "Drip",
  loops: "Loops",
  "hubspot email marketing": "HubSpot",
  "customer 360": "Salesforce",
  "adobe campaign": "Adobe",
  "mailchimp (2026 edition)": "Intuit",
  encharge: "Encharge",
  substack: "Substack",
  ghost: "Ghost",

  // HR Software
  bamboohr: "BambooHR",
  rippling: "Rippling",
  adp: "ADP",
  workday: "Workday",
  "workday hcm": "Workday",
  "workday human capital management": "Workday",
  "workday human capital management (hcm)": "Workday",
  "workday peakon employee voice": "Workday",
  gusto: "Gusto",
  "oracle hcm cloud": "Oracle",
  "oracle cloud hcm": "Oracle",
  "oracle fusion cloud hcm": "Oracle",
  "ukg pro": "UKG",
  deel: "Deel",
  hibob: "HiBob",
  personio: "Personio",
  paylocity: "Paylocity",
  paycom: "Paycom",
  paycor: "Paycor",
  "sap successfactors employee central": "SAP",
  "sap successfactors hxm suite": "SAP",
  successfactors: "SAP",
  "successfactors (sap)": "SAP",
  "hr cloud": "HR Cloud",

  // Workflow Automation
  "zapier central": "Zapier",
  "zapier central + interfaces": "Zapier",
  n8n: "n8n",
  "microsoft power automate": "Microsoft",
  "power automate": "Microsoft",
  workato: "Workato",
  tray: "Tray.ai",
  ifttt: "IFTTT",
  uipath: "UiPath",
  activepieces: "Activepieces",
  boomi: "Boomi",
  "dell boomi": "Boomi",
  relay: "Relay",
  unito: "Unito",
  "mulesoft anypoint platform": "Salesforce",
  mulesoft: "Salesforce",
  "pabbly connect": "Pabbly",
  "integromat (make)": "Make",
  "integromat (now make)": "Make",
  "integromat/make": "Make",
  integromat: "Make",
  make: "Make",
  snaplogic: "SnapLogic",
  airtable: "Airtable",
  "airtable automations": "Airtable",
  parabola: "Parabola",
  "automation anywhere": "Automation Anywhere",
  integrately: "Integrately",
  pipedream: "Pipedream",
  alloy: "Alloy",
  "slack workflow builder": "Salesforce",
  "microsoft copilot": "Microsoft",
  "azure pipelines": "Microsoft",
  "office 365": "Microsoft",
};

const RAW_PRODUCT_DISPLAY_NAMES: Record<string, string> = {
  copy: "Copy.ai",
  "copy ai": "Copy.ai",
  "copy.ai": "Copy.ai",
};

const PARENT_COMPANIES = new Map(
  Object.entries(RAW_PARENT_COMPANIES).map(([product, company]) => [
    normalizeBrandKey(product),
    company,
  ])
);

const PRODUCT_DISPLAY_NAMES = new Map(
  Object.entries(RAW_PRODUCT_DISPLAY_NAMES).map(([product, displayName]) => [
    normalizeBrandKey(product),
    displayName,
  ])
);

export function getProductDisplayName(brandName: string) {
  return PRODUCT_DISPLAY_NAMES.get(normalizeBrandKey(brandName)) ?? brandName;
}

export function getParentCompanyName(brandName: string, storedParentCompany?: string | null) {
  // Curated corrections take precedence over legacy direct-parent data. This
  // keeps the leaderboard on the immediate operating company (e.g. GitHub),
  // rather than an ultimate parent (Microsoft).
  return PARENT_COMPANIES.get(normalizeBrandKey(brandName)) ?? storedParentCompany ?? null;
}

/**
 * Always return the owner explicitly, including when product and company
 * names are identical. The table is an ownership view, so the relationship
 * should remain visible rather than being inferred from a blank cell.
 */
export function getCompanyColumnName(
  brandName: string,
  storedParentCompany?: string | null
) {
  const productName = getProductDisplayName(brandName);
  const ownerName = getParentCompanyName(productName, storedParentCompany);
  return ownerName;
}

/** Distinct owner names from the curated map (index extras, no snapshot scan). */
export function listCuratedOwnerNames(): string[] {
  return [...new Set(PARENT_COMPANIES.values())];
}

/** Product keys whose curated owner slug-matches this company URL. */
export function curatedProductKeysForCompanySlug(slug: string): string[] {
  const keys: string[] = [];
  for (const [productKey, company] of PARENT_COMPANIES) {
    if (toBrandSlug(company) === slug) keys.push(productKey);
  }
  return keys;
}
