import { prisma } from "@/lib/db";

const PROMPTS: Record<string, string[]> = {
  "AI Tools": [
    "What are the best AI tools for everyday productivity in 2026?",
    "Recommend top general-purpose AI assistants people should try.",
    "Which AI tools are most useful for research and summarizing information?",
    "What AI products would you recommend for beginners getting started with generative AI?",
    "List the leading AI tools used by startups and knowledge workers.",
    "What are the most popular AI chat and copilot products right now?",
    "Which AI tools are best for brainstorming and content ideation?",
    "Recommend well-known AI platforms that integrate into daily workflows.",
  ],
  "SaaS Software": [
    "What are the best SaaS tools for running a modern small business?",
    "Recommend popular software-as-a-service products used by startups.",
    "Which SaaS platforms are essential for team collaboration and operations?",
    "What SaaS tools would you recommend for sales and customer success teams?",
    "List widely used SaaS products for finance and subscription businesses.",
    "What are the top SaaS tools for product and project teams?",
    "Which cloud software products dominate the B2B SaaS landscape?",
    "Recommend mainstream SaaS apps that companies commonly subscribe to.",
  ],
  "AI Image / Video Tools": [
    "What are the best AI image generation tools in 2026?",
    "Recommend top AI video generation and editing products.",
    "Which AI tools are best for creating marketing visuals and thumbnails?",
    "What AI image or video products are most popular with creators?",
    "List leading generative AI tools for photos, illustrations, and short video.",
    "Which AI products would you recommend for text-to-image workflows?",
    "What are the best AI tools for text-to-video or avatar videos?",
    "Recommend well-known AI creative tools for visual content production.",
  ],
  "Developer Tools": [
    "What are the best developer tools and platforms for software teams in 2026?",
    "Recommend popular tools developers use for coding, review, and shipping software.",
    "Which developer productivity tools are most widely adopted?",
    "What tools would you recommend for cloud-native application development?",
    "List leading platforms for source control, CI/CD, and DevOps.",
    "Which AI coding assistants are most recommended for developers?",
    "What are the top tools for API development and testing?",
    "Recommend mainstream developer tools used by professional engineering teams.",
  ],
  "Marketing Tools": [
    "What are the best marketing tools for digital marketers in 2026?",
    "Recommend popular platforms for email, SEO, and campaign management.",
    "Which marketing SaaS tools are essential for growth teams?",
    "What tools would you recommend for social media marketing and scheduling?",
    "List leading products for marketing analytics and attribution.",
    "Which tools are best for content marketing and CMS-driven campaigns?",
    "What are the top advertising and marketing automation platforms?",
    "Recommend well-known marketing tools used by modern marketing teams.",
  ],
  "VPN Services": [
    "What are the best VPN services for personal privacy in 2026?",
    "Recommend top VPN providers people use to browse securely online.",
    "Which VPN services are most popular for streaming and accessing region-locked content?",
    "What VPN products would you recommend for travelers who need reliable connections abroad?",
    "List leading consumer VPN services known for strong encryption and no-logs policies.",
    "Which VPN apps are best for everyday use on phones and laptops?",
    "What are the most recommended VPN services for remote workers?",
    "Recommend well-known VPN platforms that individuals commonly subscribe to.",
  ],
  "E-commerce Platforms": [
    "What are the best ecommerce platforms for launching an online store in 2026?",
    "Recommend top ecommerce platforms merchants use to sell products online.",
    "Which ecommerce platforms are essential for building a scalable online shop?",
    "What platforms would you recommend for entrepreneurs who want to sell online?",
    "List leading ecommerce platforms for DTC brands and online retailers.",
    "Which ecommerce platforms work best for product catalogs, checkout, and orders?",
    "What are the top ecommerce platforms for managing inventory and online payments?",
    "Recommend well-known ecommerce platforms for selling online—not generic website builders.",
  ],
  "Online Course Platforms": [
    "What are the best online course platforms and MOOCs in 2026?",
    "Recommend top online course platforms for professional skills and career learning.",
    "Which cohort-based or online course platforms are most popular with adult learners?",
    "What online learning platforms would you recommend for structured courses and certificates?",
    "List leading online course platforms used for business and professional education.",
    "Which platforms are best for hosting or taking multi-week online courses?",
    "What are the most recommended MOOC and online course platforms right now?",
    "Recommend well-known online course platforms for adults pursuing skill development.",
  ],
  "Language Learning Apps": [
    "What are the best language learning apps in 2026?",
    "Recommend top language learning apps for beginners studying a new language.",
    "Which language learning apps are most popular for practicing speaking and vocabulary?",
    "What language learning apps would you recommend for daily practice on a phone?",
    "List leading language learning apps used by self-directed learners.",
    "Which apps are best for learning a foreign language with interactive lessons?",
    "What are the most recommended language learning apps for adults?",
    "Recommend well-known language learning apps that help people become conversational.",
  ],
  "Password Managers": [
    "What are the best password managers in 2026?",
    "Recommend top password manager apps for securing personal and work logins.",
    "Which password managers are most popular for storing and autofilling credentials?",
    "What password manager products would you recommend for teams that need shared vaults?",
    "List leading password managers known for encryption and cross-device sync.",
    "Which password managers are best for replacing browser-saved passwords?",
    "What are the most recommended password manager apps for everyday users?",
    "Recommend well-known password managers individuals commonly subscribe to.",
  ],
  "AI Meeting Assistants": [
    "What are the best AI meeting assistants for notes and transcripts in 2026?",
    "Recommend top AI meeting assistant tools that capture action items automatically.",
    "Which AI tools are best for meeting transcription and summaries after calls?",
    "What AI meeting assistants would you recommend for searchable meeting notes?",
    "List leading AI meeting note-takers used by remote and hybrid teams.",
    "Which AI meeting assistants help with transcripts, highlights, and follow-ups?",
    "What are the most popular AI tools for generating meeting summaries and action items?",
    "Recommend well-known AI meeting assistants for notes—not video conferencing apps.",
  ],
  "AI Cybersecurity Tools": [
    "What are the best AI cybersecurity tools for threat detection in 2026?",
    "Recommend top AI security products used for threat detection and response.",
    "Which AI-powered cybersecurity tools are most useful for SOC and security teams?",
    "What AI security tools would you recommend for detecting phishing and suspicious activity?",
    "List leading AI cybersecurity platforms for enterprise threat detection.",
    "Which AI tools are best for security operations and automated threat analysis?",
    "What are the most recommended AI-driven cybersecurity products right now?",
    "Recommend well-known AI security tools—not traditional consumer antivirus suites.",
  ],
  "Recruiting Tools": [
    "What are the best ATS and recruiting tools for hiring teams in 2026?",
    "Recommend top applicant tracking systems employers use to manage hiring pipelines.",
    "Which recruiting platforms are most popular for posting jobs and sourcing candidates?",
    "What ATS products would you recommend for startups building a hiring process?",
    "List leading recruiting tools for job boards, candidate sourcing, and interview workflows.",
    "Which AI recruiting tools help teams screen candidates and schedule interviews?",
    "What are the top recruiting platforms for employers hiring at scale?",
    "Recommend well-known ATS and recruiting tools—not general HRIS or payroll suites.",
  ],
  "Project Management Tools": [
    "What are the best project management tools for teams in 2026?",
    "Recommend top project management platforms people use to plan and track work.",
    "Which project management tools are most popular for task tracking and team collaboration?",
    "What project management products would you recommend for startups running sprints and roadmaps?",
    "List leading project management tools for assigning tasks, deadlines, and workloads.",
    "Which tools are best for managing projects with boards, timelines, and status updates?",
    "What are the most recommended project and task management apps for remote teams?",
    "Recommend well-known project management tools—not generic docs or whiteboard apps.",
  ],
  "CRM Platforms": [
    "What are the best CRM platforms for sales teams in 2026?",
    "Recommend top CRM products companies use to manage customer relationships and pipelines.",
    "Which CRM platforms are most popular for tracking leads, deals, and accounts?",
    "What CRM software would you recommend for startups building a sales process?",
    "List leading CRM platforms for sales pipeline management and customer data.",
    "Which CRM tools help teams forecast revenue and manage sales activities?",
    "What are the most recommended CRM platforms for B2B sales organizations?",
    "Recommend well-known CRM platforms—sales CRM, not generic marketing or support suites alone.",
  ],
  "Customer Support / Helpdesk": [
    "What are the best customer support and helpdesk tools in 2026?",
    "Recommend top helpdesk platforms teams use for tickets and shared inboxes.",
    "Which customer support tools are most popular for managing support tickets?",
    "What helpdesk products would you recommend for startups building customer support?",
    "List leading customer support platforms for live chat, email, and ticket workflows.",
    "Which tools are best for support teams handling customer inquiries at scale?",
    "What are the most recommended helpdesk and customer service software products right now?",
    "Recommend well-known customer support and helpdesk tools—not full CRM suites alone.",
  ],
  "Accounting & Invoicing Software": [
    "What are the best accounting and invoicing software products for small businesses in 2026?",
    "Recommend top accounting tools SMBs use for bookkeeping and invoices.",
    "Which accounting software platforms are most popular for freelancers and small companies?",
    "What invoicing and accounting products would you recommend for startups managing finances?",
    "List leading SMB accounting tools for expenses, invoices, and tax-ready books.",
    "Which tools are best for sending invoices and tracking payments for small businesses?",
    "What are the most recommended accounting software products for non-enterprise businesses?",
    "Recommend well-known accounting and invoicing software—not banks or full enterprise ERP suites.",
  ],
  "SEO / Content Tools": [
    "What are the best SEO and content tools for marketers in 2026?",
    "Recommend top SEO platforms people use for keyword research and rank tracking.",
    "Which SEO tools are most popular for site audits and technical SEO?",
    "What SEO products would you recommend for content teams optimizing pages?",
    "List leading SEO research and content optimization tools used by growth teams.",
    "Which tools are best for analyzing search rankings and competitor SEO?",
    "What are the most recommended SEO and content marketing tools right now?",
    "Recommend well-known SEO and content tools—not generic all-in-one marketing suite brand names alone.",
  ],
  "Cloud Storage": [
    "What are the best cloud storage and file sync products in 2026?",
    "Recommend top cloud drive platforms people use to store and share files.",
    "Which cloud storage services are most popular for personal and team file sync?",
    "What cloud storage products would you recommend for backing up and sharing documents?",
    "List leading cloud storage platforms for cross-device file access and collaboration.",
    "Which tools are best for secure cloud file storage and sharing links?",
    "What are the most recommended cloud drive and online storage products right now?",
    "Recommend well-known cloud storage platforms for storing and syncing files online.",
  ],
  "Design & Prototyping Tools": [
    "What are the best design and prototyping tools for product teams in 2026?",
    "Recommend top UI and graphic design platforms designers use day to day.",
    "Which design tools are most popular for interface design and interactive prototypes?",
    "What prototyping products would you recommend for shipping product mockups?",
    "List leading design tools for UI, visual design, and design systems.",
    "Which tools are best for collaborative design and handoff to engineering?",
    "What are the most recommended design and prototyping apps for digital product teams?",
    "Recommend well-known design and prototyping tools—not pure AI image or video generators.",
  ],
  "Note-taking & Knowledge Base": [
    "What are the best note-taking and knowledge base apps in 2026?",
    "Recommend top notes and wiki platforms people use to capture and share knowledge.",
    "Which note-taking apps are most popular for personal and team knowledge management?",
    "What knowledge base products would you recommend for documenting team processes?",
    "List leading notes and knowledge base tools used by knowledge workers.",
    "Which apps are best for linked notes, wikis, and searchable team documentation?",
    "What are the most recommended note-taking and knowledge base products right now?",
    "Recommend well-known notes and knowledge base apps for capturing and organizing information.",
  ],
  "Email Marketing Tools": [
    "What are the best email marketing and lifecycle campaign tools in 2026?",
    "Recommend top email marketing platforms teams use for newsletters and automations.",
    "Which email marketing tools are most popular for drip campaigns and subscriber lists?",
    "What email marketing products would you recommend for startups running lifecycle email?",
    "List leading email marketing platforms for campaigns, sequences, and deliverability.",
    "Which tools are best for marketing automation focused on email journeys?",
    "What are the most recommended email marketing software products right now?",
    "Recommend well-known email marketing tools—email and lifecycle campaigns, not generic marketing suites alone.",
  ],
  "HR Software": [
    "What are the best HR software and HRIS platforms for people teams in 2026?",
    "Recommend top HRIS products companies use for employee records and people operations.",
    "Which HR software platforms are most popular for payroll, benefits, and core HR?",
    "What HRIS products would you recommend for startups building people operations?",
    "List leading HR software for employee onboarding, time off, and HR master data.",
    "Which tools are best for managing employee information and HR workflows?",
    "What are the most recommended HRIS and HR platforms for mid-market companies?",
    "Recommend well-known HR software and HRIS platforms—not ATS or recruiting tools.",
  ],
  "Workflow Automation": [
    "What are the best no-code workflow automation tools in 2026?",
    "Recommend top automation platforms people use to connect apps without writing code.",
    "Which workflow automation tools are most popular for Zapier-style integrations?",
    "What no-code automation products would you recommend for ops teams connecting SaaS apps?",
    "List leading workflow automation platforms for triggers, actions, and multi-step flows.",
    "Which tools are best for automating handoffs between business applications?",
    "What are the most recommended no-code workflow automation products right now?",
    "Recommend well-known workflow automation tools—no-code connectors, not full developer platforms alone.",
  ],
};

async function main() {
  for (const [category, prompts] of Object.entries(PROMPTS)) {
    for (const text of prompts) {
      const existing = await prisma.prompt.findFirst({
        where: { category, promptText: text },
      });
      if (!existing) {
        await prisma.prompt.create({
          data: { category, promptText: text },
        });
      }
    }
    console.log(`Seeded ${prompts.length} prompts for ${category}`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
